//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CreatoshDAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CreatoshDB_Entities : DbContext
    {
        public CreatoshDB_Entities()
            : base("name=CreatoshDB_Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Activity> Activities { get; set; }
        public virtual DbSet<Category> Categories { get; set; }
        public virtual DbSet<Categories_In_Subjects> Categories_In_Subjects { get; set; }
        public virtual DbSet<Class> Classes { get; set; }
        public virtual DbSet<Comment> Comments { get; set; }
        public virtual DbSet<Game> Games { get; set; }
        public virtual DbSet<Grade_Level> Grade_Level { get; set; }
        public virtual DbSet<Metrics_Rating> Metrics_Rating { get; set; }
        public virtual DbSet<School> Schools { get; set; }
        public virtual DbSet<Subject> Subjects { get; set; }
        public virtual DbSet<Teacher_In_Class> Teacher_In_Class { get; set; }
        public virtual DbSet<Template> Templates { get; set; }
        public virtual DbSet<Type_of_users> Type_of_users { get; set; }
        public virtual DbSet<User> Users { get; set; }
    }
}
