//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CreatoshDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Measures_Values_In_Game
    {
        public int game_ID { get; set; }
        public string subject_name { get; set; }
        public string measure { get; set; }
        public int value { get; set; }
    
        public virtual Game Game { get; set; }
        public virtual Metrics_Rating Metrics_Rating { get; set; }
    }
}
