//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CreatoshDAL.Tests
{
    using System;
    using System.Collections.Generic;
    
    public partial class Teacher_In_Class
    {
        public int user_ID { get; set; }
        public string subject { get; set; }
        public string school_name { get; set; }
        public int grade_level { get; set; }
        public string class_name { get; set; }
    
        public virtual Class Class { get; set; }
        public virtual Subject Subject1 { get; set; }
        public virtual User User { get; set; }
    }
}
